image: gitpod/workspace-go

tasks:
  - name: Setup
    init: |
      # Install dependencies
      go mod tidy

      # Install pre-commit
      pip install pre-commit
      pre-commit install
      pre-commit install-hooks
    command: |
      # Build the project
      make build

      # Show help
      ./bin/awsmfa --help

vscode:
  extensions:
    - golang.go
    - ms-vscode.vscode-json
    - redhat.vscode-yaml
    - ms-vscode.makefile-tools
